# Interactive component

<script src="https://d3js.org/d3.v6.min.js"></script>

<button id="start" style="position: absolute; margin-left: 6px; margin-top: 4px;">Start Animation</button>
<button id="reset" style="position: absolute; margin-left: 150px; margin-top: 4px">Reset</button>

<div id="plot"></div>

<script src="scripts/draw_total_cases.js"></script>

In this project, we created a nice animation that plots the number of monthly confirmed cases around the globe in 2020 as it increases over time in real time! It draws attention to the trend of growth of the confirmed cases. In our case, the trend is undoubtedly going up since January this year. We also set up a case counter that updates to the monthly cases in each individual cases as the time series line passes through the months. The motivation for this simple yet meaningful animation is two folds. First, 

Side Note, there is a little issue with the x scale on the x axis as it appears to have shifted to the left. It is a continued issue for our interactive visualization in this chapter. Hopeful we can figure it out what went wrong with your help!