---
author:
title: "EDAV Fall 2020 PSet 4"
output: html_document
---

This assignment is designed to help you get started on the final project. Be sure to review the final project instructions (https://edav.info/project.html).

    
### 1. The Team

[8 points]

a) Who's on the team? (Include names and UNIs)


b) How do you plan to divide up the work? (Grading is on a group basis. The point of asking is to encourage you to think about this and design a plan.)


c) What is your plan for managing the git/GitHub workflow? That is, who will merge pull requests? How will you attempt to avoid conflicts? How will you communicate?


### 2. The Questions

[10 points]

List three questions that you hope you will be able to answer from your research. (It's ok if these change as your work progresses.)

a)  
  
  
b)  
  
  
c)  
  

### 3. GitHub repo

[8 points]

a) Set up your final project repository following the EDAVproject template. Provide the link to the repo.

https://github.com/xg2353/EDAV_Covid19

b) Make sure that all team members have write access to the repository and have practiced making contributions. Provide a link to the contributors page of your repository showing that all team members have made contributions to the repo (Note that we do not have the ability to see who has write access, only contributors):

https://github.com/xg2353/EDAV_Covid19/graphs/contributors

### 4. Data Sources

[8 points]

Write a draft of the [Data Sources chapter](https://edav.info/project#report-format).s


### 5. Data Transformation

[8 points]

Write a draft of the [Data Transformation chapter](https://edav.info/project#report-format)


For this project we will be using three data sets from CCSE: time series data of confirmed, recovered, and death cases. They will all be global data sets indicating number of cases of each category per each country. We called the three data sets into three different variables first. Since the data had each date in individuall columns, we had to make it into a tidy form. We used pivot_longer function to collapse the dates into a single column. After we transformed the three data sets into their tidy forms, we put them together in a single data frame variable by using the join function. Below is the R code we used.

```{r}
library(tidyverse)
library(plyr)

confirmed <- read.csv("data/time_series_covid19_confirmed_global.csv")
recovered <- read.csv("data/time_series_covid19_recovered_global.csv")
deaths <- read.csv("data/time_series_covid19_deaths_global.csv")

confirmed2 <- confirmed %>% 
  pivot_longer(cols = !c(Province.State, Country.Region, Lat, Long), names_to = "Dates", values_to = "Confirmed")
recovered2 <- recovered %>% 
  pivot_longer(cols = !c(Province.State, Country.Region, Lat, Long), names_to = "Dates", values_to = "Recovered")
deaths2 <- deaths %>% 
  pivot_longer(cols = !c(Province.State, Country.Region, Lat, Long), names_to = "Dates", values_to = "Deaths")

df <- join(confirmed2, recovered2)
df <- join(df, deaths2)
```


### 6. Missing Values

[8 points]

Write a draft of the [Missing Values chapter](https://edav.info/project#report-format)



